In [125]:
import re
import numpy as np
import math

Rafael Hinojosa López

A01705777

28-05-2023

Desarrollo de aplicaciones avanzadas de ciencias computacionales (Gpo 301)

##### Read texts

In [126]:
with open("./text1.txt", 'r', encoding='utf-8') as f:
    text1 = f.read()

In [127]:
with open("./text2.txt", 'r', encoding='utf-8') as f:
    text2 = f.read()

##### Preprocess text

In [128]:
text1 = text1.lower()
text2 = text2.lower()

text1 = re.findall(r'\w+', text1)
text2 = re.findall(r'\w+', text2)

combined_text = text1 + text2
combined_text

['this',
 'is',
 'a',
 'good',
 'day',
 'what',
 'day',
 'is',
 'today',
 'good',
 'day',
 'is',
 'a',
 'this',
 'today',
 'is',
 'what',
 'day']

###### Create one directed graph per text where vertex (key of the dict) _v_ represents a word in the text and contains a list of all the words that appear right after that word

In [129]:
words1 = {}
words2 = {}

for word in combined_text:
    words1[word] = []
    words2[word] = []

# Create graph for text1
for i in range(1, len(text1)):
    origin_word = text1[i-1]
    destination_word = text1[i]
    words1[origin_word].append(destination_word)

# Create graph for text2
for i in range(1, len(text2)):
    origin_word = text2[i-1]
    destination_word = text2[i]
    words2[origin_word].append(destination_word)
    
print(words1)
print(words2)

{'this': ['is'], 'is': ['a', 'today'], 'a': ['good'], 'good': ['day'], 'day': ['what', 'is'], 'what': ['day'], 'today': []}
{'this': ['today'], 'is': ['a', 'what'], 'a': ['this'], 'good': ['day'], 'day': ['is'], 'what': ['day'], 'today': ['is']}


###### Crear un arreglo donde se mapeen las palabras con su posicion en el grafo

In [130]:
words1_index = {}
words2_index = {}

index = 0
for word in words1:
    words1_index[word] = index
    index += 1

index = 0
for word in words2:
    words2_index[word] = index
    index += 1

print(words1_index)
print(words2_index)

{'this': 0, 'is': 1, 'a': 2, 'good': 3, 'day': 4, 'what': 5, 'today': 6}
{'this': 0, 'is': 1, 'a': 2, 'good': 3, 'day': 4, 'what': 5, 'today': 6}


###### Create transition matrices

- inicializar un array de length palabras con 0s
- llenar las que ya se tienen guardadas en su indice correspondiente y ya!! hacer append de la lista a la matriz wuuu
/ ok necesitamos que las matrices y asi... estar tratando con todas las palabras, no solo con las actuales...

con esto ponemos ok... mat1[map[i]] = 1 / total o asi... o sea aja... 




In [131]:
mat1 = []
mat2 = []

len1 = len(words1)
len2 = len(words2)

for word in words1:
    list1 = [0 for i in range(len1)]

    val1 = 0
    if len(words1[word]) != 0:
        val1 = 1 / len(words1[word])

    for next_word in words1[word]:
        next_word_index = words1_index[next_word]
        list1[next_word_index] += val1        

    mat1.append(list1)


for word in words2:
    list2 = [0 for i in range(len2)]
    
    val2 = 0
    if len(words2[word]) != 0:
        val2 = 1 / len(words2[word])

    for next_word in words2[word]:
        next_word_index = words2_index[next_word]
        list2[next_word_index] += val2        

    mat2.append(list2)

mat1 = np.array(mat1)
mat2 = np.array(mat2)

print(mat1)
print(mat2)

[[0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.5]
 [0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]]
[[0.  0.  0.  0.  0.  0.  1. ]
 [0.  0.  0.5 0.  0.  0.5 0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]]


##### Calculate similarity

In [132]:
BT = mat2.transpose()
C = np.matmul(BT, mat1)
prod_int = np.trace(C)

norm_A = math.sqrt(np.trace(np.matmul(mat1.transpose(), mat1)))
norm_B = math.sqrt(np.trace(np.matmul(mat2.transpose(), mat2)))

cos_ang = prod_int / (norm_A * norm_B)


print('A | Mat1 = \n' + str(mat1) + '\n')
print('B | Mat2 = \n' + str(mat2) + '\n')
print('BT | Transpose of Mat2 = \n' + str(BT) + '\n')
print('C = ' + str(C) + '\n')
print('Prod int = ' + str(round(prod_int, 4)) + '\n')
print('Norm A | Norm Mat1 = ' + str(round(norm_A, 4)) + '\n')
print('Norm B | Norm Mat2 = ' + str(round(norm_B, 4)) + '\n')
print('Cosine angle = ' + str(round(cos_ang, 4)) + '\n')

A | Mat1 = 
[[0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.5]
 [0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]]

B | Mat2 = 
[[0.  0.  0.  0.  0.  0.  1. ]
 [0.  0.  0.5 0.  0.  0.5 0. ]
 [1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]]

BT | Transpose of Mat2 = 
[[0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  1. ]
 [0.  0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  1.  0. ]
 [0.  0.5 0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0. ]]

C = [[0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.5  0.   0.   0.   0.5  0.  ]
 [0.   0.   0.25 0.   0.   0.   0.25]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   2.   0.   0.  ]
 [0.   0.   0.25 0.   0.   0.   0.25]
 [0.   1.   0.   0.   0.   0.   0.  ]]

Prod int = 2.75

Norm